Define Roles and Responsibilities
IntersectMBO/cardano-addresses pull request #250
Opened 2024-05-08 10:47 UTC by HeinrichApfelmus

This pull request defines roles and responsibilities for this repository, following the [Project management policy](https://input-output-hk.github.io/cardano-engineering-handbook/policy/project/index.html#project-management) of the [Cardano Engineering Handbook][1].

For the Haskell components, the @cardano-foundation is willing to take responsibility; I have written down corresponding names.

For the CI and JavaScript parts, @intersectmbo will have to be responsible. I have put down some tentative names there, but please feel free to change them.

  [1]: https://input-output-hk.github.io/cardano-engineering-handbook/policy/project/index.html#roles-and-responsibilities

2024-05-08 11:34 UTC, Unisay approved these changes

2024-05-08 12:40 UTC, paweljakubas approved these changes

2024-05-08 12:57 UTC, Anviking approved these changes

2024-05-09 03:51 UTC, jonathanknowles approved these changes

2024-06-05 17:47 UTC, Crypto2099 commented
Attn: @HeinrichApfelmus I have been asked by Intersect to serve provisionally as the Intersect-appointed maintainer for this repo and am happy to help share the lift w.r.t. the JS portions of the library if CF will continue maintaining and supporting the Haskell portions.

With that said and in mind, I will start reviewing old pull requests and issues to either assign or close them as necessary and begin  to bring this repository in line with Intersect MBO standards as they are currently being defined.

2024-06-06 15:03 UTC, Crypto2099 requested changes

2024-06-06 15:03 UTC, Crypto2099 commented on CODEOWNERS
> +nix/              @hamishmack
```suggestion
# CICD
.github/          @Crypto2099 
nix/              @Crypto2099 
```

2024-06-07 14:11 UTC, Crypto2099 approved these changes

2024-06-12 21:23 UTC, merged