Add DRep and CC key types
IntersectMBO/cardano-addresses pull request #251
Opened 2024-06-09 12:37 UTC by disassembler

dependent on #231

2024-06-10 14:53 UTC, Crypto2099 reviewed
Couple of minor things noticed but overall looking like good progress

2024-06-10 14:53 UTC, Crypto2099 commented on cabal.project
> +-- you need to run if you change them
Is this legacy code from another source? Do we need to update CONTRIBUTING with relevant details?

2024-06-10 14:53 UTC, Crypto2099 commented on command-line/lib/Command/Key/WalletId.hs
> +            [ "A wallet ID is a 40-digit hexadecimal pretty derived " :: Text
This looks like a situation where "find + replace" found a legitimate use of the word "string" and replaced it with pretty even though that's not desired behavior! :D

```suggestion
            [ "A wallet ID is a 40-digit hexadecimal string derived " :: Text
```

2024-06-10 15:00 UTC, Crypto2099 commented
cc: @aleeusgr please see changes here and would love your feedback on the Nix build issues we're still seeing!

2024-06-11 06:19 UTC, paweljakubas commented on core/lib/Cardano/Address/Style/Shelley.hs
> +    -> Shelley 'DelegationK XPrv
we should have here `'DRepK`

2024-06-11 06:20 UTC, paweljakubas commented on core/lib/Cardano/Address/Style/Shelley.hs
> +    -> Shelley 'DelegationK XPrv
we should have here `'CCColdK`

2024-06-11 06:20 UTC, paweljakubas commented on core/lib/Cardano/Address/Style/Shelley.hs
> +    -> Shelley 'DelegationK XPrv
we should have here `'CCHotK`

2024-06-11 06:29 UTC, paweljakubas requested changes
So we have somewhere decided to use the following derivation paths
`1852H/1815H/0H/3/0` for DRep
`1852H/1815H/0H/4/0` for CCCold
`1852H/1815H/0H/5/0` for CCHot
Correct?

Also it would be good to adjust https://github.com/IntersectMBO/cardano-addresses/blob/master/core/test/Cardano/Address/Style/ShelleySpec.hs
(extend role generator and add golden here)
Finally, cli support would need to be added (of course could be in separate PR)

2024-06-24 08:57 UTC, paweljakubas commented
cherry-picked the commit and finished here https://github.com/IntersectMBO/cardano-addresses/pull/259

2024-06-24 08:57 UTC, closed without merging